import type { Metadata } from "next";
import { Kodchasan } from "next/font/google";
import "./globals.css";
import { Providers } from '@/providers';

const kodchasan = Kodchasan({
  variable: "--font-kodchasan-sans",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${kodchasan.variable} antialiased font-sans max-w-screen-xl mx-auto mb-8`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
